/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTEREST_H_RPCGEN
#define _INTEREST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct rate {
	float principal;
	float intrest;
	float time;
};
typedef struct rate rate;

#define RATE_PROG 0x2342362
#define RATE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define rate_of_interest 1
extern  float * rate_of_interest_1(rate *, CLIENT *);
extern  float * rate_of_interest_1_svc(rate *, struct svc_req *);
extern int rate_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define rate_of_interest 1
extern  float * rate_of_interest_1();
extern  float * rate_of_interest_1_svc();
extern int rate_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_rate (XDR *, rate*);

#else /* K&R C */
extern bool_t xdr_rate ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTEREST_H_RPCGEN */
