/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "interest.h"

bool_t
xdr_rate (XDR *xdrs, rate *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->principal))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->intrest))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->time))
		 return FALSE;
	return TRUE;
}
